### ISSUE TITLE
"Error parsing audit JSON: missing field 'dev' at line x column y"

### ISSUE THREAD

**Issue by cbonaco1** [mozilla-services/audit-filter#37]
Hi,
We are seeing an issue running `npm audit --json | audit-filter` where we are getting the error mentioned in the title. 
Below is the JSON output from `npm audit --json`:

![image](https://user-images.githubusercontent.com/8948249/61828792-820e8480-ae35-11e9-9bb4-e2641b4922ed.png)

It looks like `audit-filter` is expecting a `dev` flag inside of the `findings` object; however for some reason `npm audit --json` is not generating it (Node and npm versions listed below). Could this be an error on the part of `npm audit` ? Any guidance is appreciated!

audit-filter version: `0.4.3`
Node version: `8.15.1`
npm version: `6.4.1`

**Comment by mkls** [comment]
The same thing just started happening for us, too.
My guess is that npm's response for audit requests have slightly changed.

**Comment by cilindrox** [comment]
Same boat, wasn't expect the response to be bound to anything other than `npm`'s binary - but as @mkls mentioned, looks like it's due to an upstream update.

**Comment by g-k** [comment]
Thanks for bringing this up! I'm working on a fix in #38.

**Comment by cbonaco1** [comment]
No longer seeing the error in version 0.5.0. Thank you @g-k !
